# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  commons: commons.yml

services:
  http:
    AppsService:
      auth: true
      base-path: /app/{appName}
      path-parameters:
        appName: commons.AppName
      endpoints:
        get:
          display-name: Get App
          method: GET  # TODO verify method
          path: /
          response: GetAppResponse
          examples:
            - path-parameters:
                appName: $commons.AppName.Example
              response:
                body: $GetAppResponse.Example
        logs:
          display-name: Get App logs
          method: GET  # TODO verify method
          path: /logs
          response: string
          examples:
            - path-parameters:
                appName: $commons.AppName.Example
              response:
                body: |
                  log line 1
                  log line 2
                  log line 3
        delete:
          display-name: Delete App
          method: DELETE  # TODO verify method
          path: /delete
          request:
            name: GetAppRequest
            query-parameters:
              forceDestroy: optional<boolean>
          response: string
          examples:
            - path-parameters:
                appName: $commons.AppName.Example
              response:
                body: Deleted app

types:
  GetAppResponse:
    extends: commons.Deployment
    properties:
      secret: string
    examples:
      - name: Example
        value:
          appId: $commons.AppId.Example
          deploymentId: $commons.DeploymentId.Example
          regionalContainerTags: []
          containerPort: 100
          transportType: tcp
          roomsPerProcess: 10
          requestedCPU: 32
          requestedMemoryMB: 4096
          deployedBy: username
          deployStartedAt: "2023-01-11T23:14:02+00:00"
          deployFinishedAt: "2023-01-11T23:14:42+00:00"
          status: completed
          secret: app-secret